package pl.simple.zegarki.basic;



public enum WatchType {
ANALOGWRISTWATCH,DIGITALWRISTWATCH,CUCKOOCLOCK,	CLOCKSWING,SWISSWATCH;

public static final WatchType[] ALL = { ANALOGWRISTWATCH,DIGITALWRISTWATCH,CUCKOOCLOCK,CLOCKSWING,SWISSWATCH };
}
